name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        env:
          HUSKY_SKIP_INSTALL: 1
        run: yarn install --frozen-lockfile
      - name: Lint
        if: github.event_name == 'pull_request'
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Deploy
        if: github.event_name != 'pull_request' && !contains(github.event.head_commit.message, '[skip ci]')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
